# This allows us to merge arrays for Exclude rules on AllCops or a specific cop
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 200
